CREATE TABLE PRICES
(
    ID         UUID,
    BRAND_ID   INT,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY   INT,
    PRICE      DECIMAL(10, 2),
    CURRENCY   VARCHAR(3),
    PRIMARY KEY (ID)
);

ALTER TABLE PRICES
    ADD COLUMN TIME_ZONE VARCHAR(255);

CREATE INDEX IDX_PRODUCT_ID ON PRICES (PRODUCT_ID);
CREATE INDEX IDX_BRAND_ID ON PRICES (BRAND_ID);
CREATE INDEX IDX_START_DATE ON PRICES (START_DATE);
CREATE INDEX IDX_END_DATE ON PRICES (END_DATE);
